###########
# site.url, site.title

title: 'Arena Squash och Padel'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: /
url:  'http://arenasop.github.io'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

